<?php
session_start();
require_once('../constants.php');
if (empty($_SESSION['table']) || isset($_POST['reset'])) {
    //load table
    $groupcsvfp = '../group.csv';
    $groupcsv = fopen($groupcsvfp, 'r');
    $group = array();

    while (($data = fgetcsv($groupcsv)) !== false) {
        $group[] = $data;
    }
    $_SESSION['table'] = $group;
} else {
    $group = $_SESSION['table'];
}
?>
<style>
th{
    width: 30px;
    height: 30px;
}
</style>
<p>The table generated by this page will have elements ordered in the same way as the <a href="https://alexscully.com/archive/aa_group_journal/page_1/cayleytable.php">Cayley table page</a>.</p>
<form method="post" action="subgroupviewer.php">
    <?php 
        echo "<table><tr>";
        $includedelements = array();
        foreach($group[0] as $element){
            echo "<td><label for='$element'>$element</label></td>";
        }
        echo "</tr><tr>";
        foreach($group[0] as $element){
            if(isset($_POST[$element])){
                echo "<td><input type='checkbox' id='$element' name='$element' checked></td>";
                $includedelements[] = $element;
            } else{
                echo "<td><input type='checkbox' id='$element' name='$element'></td>";
            }
        }
        echo "</table></tr>";
    ?>
    <br><input type="submit" value="view subset"><br>
</form>
<?php
echo "<table>";
$i = 0;
$issubgroup = true;
foreach ($group as $row) {
    if(in_array($group[0][$i], $includedelements)){
        echo "<tr>";
        $j = 0;
        foreach ($row as $entry) {
            $entry = trim($entry);
            if(in_array($group[0][$j], $includedelements)){
                echo '<th style = "background-color:' . COLORS[$entry] . ';">' . strval($entry) . "</th>";
                if(!in_array($entry, $includedelements)){
                    $issubgroup = false;
                }
            }
            $j += 1;
        }
        echo "</tr>";
    }
    $i += 1;
}
echo "<table><br>";
if($issubgroup && count($includedelements) > 0){
    echo "This set is a subgroup.";
} else {
    echo "This set is not a subgroup.";
}
?>