<?php
session_start();
require_once('../constants.php');
if (empty($_SESSION['table']) || isset($_POST['reset'])) {
    //load table
    $groupcsvfp = '../group.csv';
    $groupcsv = fopen($groupcsvfp, 'r');
    $group = array();

    while (($data = fgetcsv($groupcsv)) !== false) {
        $group[] = $data;
    }
    $_SESSION['table'] = $group;
} else {
    $group = $_SESSION['table'];
}
?>
<style>
th{
    width: 30px;
    height: 30px;
}
</style>
<p>The tables generated by this page will have elements ordered in the same way as the <a href="https://alexscully.com/archive/aa_group_journal/page_1/cayleytable.php">Cayley table page</a>.</p>

<?php
$subgroups = array(
    array('2'),
    array('2', '8'),
    array('2', '6'),
    array('2', 'a'),
    array('2', '1'),
    array('2', '8', '6', '1'),
    array('2', '5'),
    array('2', '8', 'a', '5'),
    array('2', '3'),
    array('2', '6', 'a', '3'),
    array('2', '1', '5', '3'),
    array('2', 'h'),
    array('2', 'a', '1', 'h'),
    array('2', '6', '5', 'h'),
    array('2', '8', '3', 'h'),
    array('2', '8', '6', 'a', '1', '5', '3', 'h'),
    array('2', 'a', 'd', '4'),
    array('2', 'a', 'g', 'c'),
    array('2', '8', 'a', '5', 'd', '4', 'g', 'c'),
    array('2', '5', 'i', 'b'),
    array('2', '5', 'f', '7'),
    array('2', '8', 'a', '5', 'i', 'b', 'f', '7'),
);
foreach($subgroups as $subgroup){
    echo "<table>";
    $i = 0;
    $issubgroup = true;
    foreach ($group as $row) {
        if(in_array($group[0][$i], $subgroup)){
            echo "<tr>";
            $j = 0;
            foreach ($row as $entry) {
                $entry = trim($entry);
                if(in_array($group[0][$j], $subgroup)){
                    echo '<th style = "background-color:' . COLORS[$entry] . ';">' . strval($entry) . "</th>";
                    if(!in_array($entry, $subgroup)){
                        $issubgroup = false;
                    }
                }
                $j += 1;
            }
            echo "</tr>";
        }
        $i += 1;
    }
    echo "<table><br>";
}
?>